config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/blogs' => 'blogs#index'
  get '/blogs/new' => 'blogs#new'
  post '/blogs' => 'blogs#create'
  get '/blogs/':id => 'blogs#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController



	def index
		@blogs = Blog.all
	end 
	def new
		@blog = Blog.new
	end
	def create
		@blog = Blog.new(blog_params)
		@blog.save
		redirect_to '/blogs'
	end

	private

	def  blog_params
		params.require(:blog).permit(:title, :body, :category)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/index.html.erb
<header>
    <h1 class="headline">
      <a href="#">CARAVAN</a>
    </h1>
    <div class="social">
      <i class="fa fa-facebook-square"></i>
      <i class="fa fa-twitter-square"></i>
      <i class="fa fa-instagram"></i>
    </div>
  </header>

  <nav>
    <ul class="nav-list">
      <li class="nav-list-item">
        <a href="#">Home</a>
      </li>
      <li class="nav-list-item">About</li>
      <li class="nav-list-item">Topic</li>
    </ul>
  </nav>

  <div class="main-visual">
    <div class="main-visual-content">
      <p class="main-visual-text">
        The world is a book<br>
        and those who do not travel<br>
        read only one page.
      </p>
      <p class="main-visual-name">
        St. Augustine
      </p>
    </div>
  </div>

  <main class="clearfix">
    <section class="blog">
      <h2 class="blog-headline">Recent Blogs</h2>
      <div class="blog-box">
        <!-- 第三回でここから書き換える -->
        <% @blogs.each do |blog| %>
        <div class="blog-item clearfix">
          <%= image_tag "img/forest.jpg", class:"blog-image" %>
          <section class="blog-text">
            <h3 class="blog-text-headline">
              <%= blog.title %>
            </h3>
            <p class="blog-date">June 19, 2017</p>
            <span class="category"><!  Nature  >
            </span>
          </section>
        </div>
        <% end %>
        <!-- ここまで -->
      </div>
      <div class="pagination">
        <p><<</p>
        <p><</p>
        <p>1</p>
        <p>2</p>
        <p>3</p>
        <p>></p>
        <p>>></p>
      </div>
    </section>
    <div class="sidebar">
      <section class="popular">
        <h2 class="sidebar-headline">Popular</h2>
        <div class="sidebar-contents">
          <p class="popular-text">To solve old problems,<br>study new species</p>
          <p class="popular-text">Why Earth may someday<br>look like Mars</p>
          <p class="popular-text">What will humans look<br>like in 100 years?</p>
          <p class="popular-text">How to grow a forest<br>in your backyard</p>
          <p class="popular-text">How humans could evolve<br>to survive in space</p>
        </div>
      </section>
      <section class="instagram">
        <h2 class="instagram-headline">Instagram</h2>
        <div class="sidebar-contents clearfix">
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
        </div>
      </section>
      <section class="categories">
        <h2 class="categories-headline">Categories</h2>
        <div class="sidebar-contents">
          <p class="categories-text">Technology(15)</p>
          <p class="categories-text">Business(23)</p>
          <p class="categories-text">Entertainment(12)</p>
          <p class="categories-text">Nature(32)</p>
          <p class="categories-text">Education(9)</p>
          <p class="categories-text">Adventure(23)</p>
          <p class="categories-text">Communication(14)</p>
        </div>
      </section>
    </div>
  </main>

  <footer>
    <p class="footer-text">© All rights recerved by Infratop.Inc.</p>
  </footer>

app/views/blogs/new.html.erb
<p>新規投稿</p>

<%= form_for(@blog) do |f| %>
  <p>タイトル</p><%= f.text_field :title %><br>
  <p>本文</p><%= f.text_area :body %><br>
  <p>カテゴリー</p><%= f.text_field :category %><br>
  <%= f.submit "送信" %>
<% end %>

app/views/blogs/show.html.erb
<header>
    <h1 class="headline">
      <%= link_to "CARAVAN", blogs_path %>
    </h1>
    <div class="social">
      <i class="fa fa-facebook-square"></i>
      <i class="fa fa-twitter-square"></i>
      <i class="fa fa-instagram"></i>
    </div>
  </header>

  <nav>
    <ul class="nav-list">
      <li class="nav-list-item">
        <a href="#">Home</a>
      </li>
      <li class="nav-list-item">About</li>
      <li class="nav-list-item">Topic</li>
    </ul>
  </nav>

  <div class="main-visual">
      <div class="main-visual-content">
        <p class="main-visual-text">
          The world is a book<br>
          and those who do not travel<br>
          read only one page.
        </p>
        <p class="main-visual-name">
          St. Augustine
        </p>
      </div>
    </div>

  <main class="clearfix">
    <section class="single-blog">
      <h2 class="blog-headline">Blog</h2>
      <section class="blog-box">
            <h3 class="blog-box-headline">
              <!  タイトルを表示　　＞
            </h3>

            <div class="blog-box-content">
              <p class="category">
              ＜！　カテゴリーを表示　　＞
              </p>
              <p class="blog-date">
                June 19, 2017
          </p>
            </div>

              <div class="single_image"></div>
              <p class="single_text">
                ＜！　　本文を表示。　　＞
              </p>

          <a href="#">編集</a>
          <a href="#">削除</a>

          <div class="author_case clearfix">
            <div class="author_image"></div>
              <div class="author_box">
                <p class="author_name">By JOHN SMITH / Photographer</p>
                <p class="author-text">His black and white landscapes, often captured at times<br>of the day and night when the light is fleeting, or in poor<br>weather conditions, such as rain, fog, or snow, are<br>reminiscent of the calm in a storm all with an ethereal<br>quality.
                </p>
              </div>
            </div>
        </section>
      </section>

    <div class="sidebar">
      <section class="popular">
        <h2 class="sidebar-headline">Popular</h2>
        <div class="sidebar-contents">
          <p class="popular-text">To solve old problems,<br>study new species</p>
          <p class="popular-text">Why Earth may someday<br>look like Mars</p>
          <p class="popular-text">What will humans look<br>like in 100 years?</p>
          <p class="popular-text">How to grow a forest<br>in your backyard</p>
          <p class="popular-text">How humans could evolve<br>to survive in space</p>
        </div>
      </section>
      <section class="instagram">
        <h2 class="instagram-headline">Instagram</h2>
        <div class="sidebar-contents clearfix">
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
        </div>
      </section>
      <section class="categories">
        <h2 class="categories-headline">Categories</h2>
        <div class="sidebar-contents">
          <p class="categories-text">Technology(15)</p>
          <p class="categories-text">Business(23)</p>
          <p class="categories-text">Entertainment(12)</p>
          <p class="categories-text">Nature(32)</p>
          <p class="categories-text">Education(9)</p>
          <p class="categories-text">Adventure(23)</p>
          <p class="categories-text">Communication(14)</p>
        </div>
      </section>
    </div>
  </main>
  <footer>
    <p class="footer-text">© All rights recerved by Infratop.Inc.</p>
  </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Caravan</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>